var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};$jscomp.arrayFromIterator=function(a){for(var b,d=[];!(b=a.next()).done;)d.push(b.value);return d};
var System={version:2,config:null,member:{},time:null,focus_timer:null,content:"list",search:{},SerialNumber:null,char_default:{name:"",game_sn:"",wolf_win:0,human_win:0,wolf_lose:0,human_lose:0,item:{money:150},game_day:"0",game_time:"",game_end:"",vote:{0:{value:"",time:""}},pass:{0:{value:"",time:""}},wolf:{0:{value:"",time:""}},divine:{0:{value:"",time:""}},psychic:{0:{value:"",time:""}},guard:{0:{value:"",time:""}},human:{0:{value:"",time:""}},ready:"no",dead:{status:"live"}},c_s_word:{name:"\u5e33\u865f\u540d\u7a31",
wolf_win:"\u72fc\u52dd\u5834\u6578",human_win:"\u4eba\u52dd\u5834\u6578",wolf_lose:"\u72fc\u6557\u5834\u6578",human_lose:"\u4eba\u6557\u5834\u6578",item:"\u6301\u6709\u91d1\u9322"},create_game_row:{name:{name:"\u904a\u6232\u540d\u7a31",type:"text",value:"\u904a\u6232\u540d\u7a31"},game_password:{name:"\u9032\u5165\u5bc6\u78bc",type:"text",value:"\u9032\u5165\u5bc6\u78bc"},game_memo:{name:"\u904a\u6232\u8aaa\u660e",type:"textarea",value:"\u904a\u6232\u8aaa\u660e"},game_nickname:{name:"\u6b64\u5c40\u89d2\u8272\u540d\u7a31",
type:"text",value:"\u6b64\u5c40\u89d2\u8272\u540d\u7a31"},char_count:{name:"\u904a\u6232\u4eba\u6578",type:"number",value:8},wolf_count:{name:"\u4eba\u72fc\u6578\u91cf",type:"number",value:2},divine_count:{name:"\u5148\u77e5\u6578\u91cf",type:"number",value:1},guard_count:{name:"\u5b88\u885b\u6578\u91cf",type:"number",value:1},psychic_count:{name:"\u9748\u5a92\u6578\u91cf",type:"number",value:1}},job_word:{psychic:"\u9748\u5a92",guard:"\u5b88\u885b",wolf:"\u4eba\u72fc",divine:"\u5148\u77e5",human:"\u6751\u6c11"},
_sessionStorage:{}};window.onload=function(){var a=document.createElement("div");a.id="Mask";document.body.appendChild(a);document.body.className="loading"};eval(atob("dmFyIERCID0gZmlyZWJhc2U7REIuaW5pdGlhbGl6ZUFwcCh7ZGF0YWJhc2VVUkw6ICJodHRwczovL2tmc3dvbGYtZGVmYXVsdC1ydGRiLmZpcmViYXNlaW8uY29tIn0pO0RCID0gREIuZGF0YWJhc2UoKTs="));DB.ref("/system/config").once("value",function(a){System.config=a.val();document.title="\u7db2\u9801\u72fc\u4eba\u3010\u7248\u672c:"+System.version+"\u3011";Main()});
function SortData(a,b,d){var c=[],g;for(g in a){var h=c.length;c[h]=a[g];c[h]._sort=a[g][b]}1==(void 0===d?1:d)?c.sort(function(f,e){return f._sort>e._sort?-1:1}):c.sort(function(f,e){return f._sort>e._sort?1:-1});for(g in c)delete c[g]._sort;return c}
function RowMake(a,b,d){for(var c in a){var g=document.createElement("input");"textarea"===a[c].type&&(g=document.createElement("textarea"),g.defaultValue=a[c].value);var h=document.createElement("span");g.id=c;for(var f in a[c])g.setAttribute(f,a[c][f]);h.innerHTML=a[c].span||"";if(void 0!==a[c].event)for(var e in a[c].event)g.addEventListener(e,a[c].event[e]);var k=document.createElement("div");k.className="row";k.appendChild(h);k.appendChild(g);b.appendChild(k)}document.querySelectorAll("#Menu ul>div").forEach(function(l,
m){l.innerHTML=""});document.querySelector("div#"+d).appendChild(b);setTimeout(function(){document.querySelector("div#"+d).style.height=document.querySelector("div#"+d+" div#Main").clientHeight+"px"},0)}
function ListMake(a,b,d,c){var g=document.createElement("table");g.id="ListTable";var h=document.createElement("tr"),f;for(f in a){var e=document.createElement("td");e.innerHTML=a[f].title;e.setAttribute("id",a[f].id||"");e.className=a[f].title_class||"";for(var k in a[f].title_event)e.addEventListener(k,a[f].title_event[k]);h.appendChild(e)}g.appendChild(h);for(var l in b){h=document.createElement("tr");for(f in a){e=document.createElement("td");e.innerHTML=b[l][a[f].html];e.setAttribute("id",b[l][a[f].id]||
"");e.className=a[f]["class"]||"";e.className=b[l]["class"]||e.className;for(k in a[f].event)"remove"!==b[l].event&&e.addEventListener(k,a[f].event[k]);h.appendChild(e)}g.appendChild(h)}d.appendChild(g);document.querySelectorAll("#Menu ul>div").forEach(function(m,n){m.innerHTML=""});document.querySelector("div#"+c).appendChild(d);setTimeout(function(){document.querySelector("div#"+c).style.height=document.querySelector("div#"+c+" div#Main").clientHeight+"px"},0)}
function ServerTime(){firebase.database().ref("/").update({ServerTime:firebase.database.ServerValue.TIMESTAMP}).then(function(a){firebase.database().ref("/").once("value").then(function(b){b=b.val();b=b.ServerTime;System.time=b;clearInterval(System._timer);document.createElement("div");System._timer=setInterval(function(){System.time+=100;System.SerialNumber=System.time.toString().substr(1);document.querySelector("#Time")&&(document.querySelector("#Time").innerHTML="\u3010"+DateFormat(new Date(System.time))+
"\u3011")},100);setTimeout(function(){document.querySelector("div#Mask").className="off";setTimeout(function(){document.querySelector("div#Mask").style.display="none";document.body.className=""},500)},100);console.log("server time: ",b)},function(b){console.log("coulnd nt reach to the server time !")})},function(a){console.log("set time error:",a)})}
function DateFormat(a,b){b=void 0===b?!1:b;var d=a.toString().split(" "),c=d[4];d=d[3]+"/"+parseInt((new Date(a)).getMonth()+1)+"/"+(new Date(a)).getDate();!0===b&&(d="");!1===b&&(d+=" ");"<BR>"===b&&(d+="<BR>");return d+=c.split(":")[0]+":"+c.split(":")[1]+":"+c.split(":")[2]}function Shuffle(a){for(var b=a.length-1;0<b;b--){var d=Math.floor(Math.random()*(b+1)),c=$jscomp.makeIterator([a[d],a[b]]);a[b]=c.next().value;a[d]=c.next().value}}
function P(a){a=$jscomp.makeIterator(a);a=$jscomp.arrayFromIterator(a);Shuffle(a);return a.join("")}function Focus(a){clearInterval(System.focus_timer);System.focus_timer=setInterval(function(){document.querySelectorAll(a).forEach(function(b){b.classList.toggle("focus")})},300)}function CheckMobile(){return-1!==navigator.userAgent.indexOf("Mobile")?!0:!1};